# eksctl create nodegroup -f eks-nodegroup-managed-ng-private-builder.yaml
# eksctl delete nodegroup --approve -f eks-nodegroup-managed-ng-private-builder.yaml
#
# NOTE BE CAREFULL OF CONFIG-MAP MN-NODE INSTANCE ROLES
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ab3-eks
  region: us-east-2

managedNodeGroups:
  - name: managed-ng-builder
    instanceType: t3.large
    # launch nodegroup in private subnets
    privateNetworking: true
    minSize: 3
    desiredCapacity: 6
    maxSize: 6
    availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]
    volumeSize: 20

    labels: {role: builder}
    tags:
      nodegroup-role: builder