apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-1
  namespace: deployment-blue
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/i1b1y7y0/php-apache:8.0.3
          ports:
            - name: http
              containerPort: 80