#02-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  name: deployment-1
  namespace: deployment-1
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: public.ecr.aws/i1b1y7y0/php-apache:8.0.3
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: deployment-1
  name: php-service-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: php