#
#
# NOTE the EKS documentation for the EXAMPLE CONFIGMAP is WRONG (formating)
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::308364868471:user/rernst
      username: rernst
        - groups:
      - system:masters
      userarn: arn:aws:iam::308364868471:user/rernst
      username: rernst 
    - groups:
      - system:masters
      userarn: arn:aws:sts::308364868471:assumed-role/ab3workshop-admin
      username: ab3workshop-admin 
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::308364868471:role/eksctl-ab3-eks-nodegroup-managed-NodeInstanceRole-QK7VH8E0Z3QH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::308364868471:role/eksctl-ab3-eks-nodegroup-managed-NodeInstanceRole-BWBLN5KZAXD5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::308364868471:role/eksctl-ab3-eks-cluster-ServiceRole-BAAU5VTT2XS4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::308364868471:role/eksctl-ab3-eks-cluster-FargatePodExecutionRole-CE0TYV23IJ55
      username: system:node:{{SessionName}}