#eksctl create fargateprofile -f fp-dev.yaml
# NOTE - THIS CREATES TWO PROFILES
#
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ab3-eks
  region: us-east-2

fargateProfiles:
  - name: fp-development
    selectors:
      # All workloads in the "development" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: development
  - name: fp-test
    selectors:
      # All workloads in the "fp-test" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: test
        labels:
          env: test
          checks: passed