#eksctl create fargateprofile -f fargate-profile-example.yaml
#
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ab3-eks
  region: us-east-2

fargateProfiles:
  - name: fp-deployment-fargate
    selectors:
      # All workloads in the "deployment-fargate" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: deployment-fargate
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed