apiVersion: v1
kind: Service
metadata:
  namespace: deployment-red
  name: php-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: php