apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-1
  namespace: deployment-red
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: public.ecr.aws/i1b1y7y0/php-apache:8.0.3
          ports:
            - name: http
              containerPort: 80