apiVersion: v1
kind: Service
metadata:
  name: ab3-app-frontend
  namespace: development
spec:
  selector:
    app: ab3-app-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80