apiVersion: v1
kind: Service
metadata:
  name: ab3-ssl-frontend
  namespace: development
spec:
  selector:
    app: ab3-ssl-frontend
  type: LoadBalancer
  ports:
  - name: https
    port: 443
  - name: http
    port: 80