apiVersion: v1
kind: Service
metadata:
  name: ab3-ssl-frontend
  namespace: development
spec:
  selector:
    app: ab3-ssl-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 443
      targetPort: 443